services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - '6379:6379'
  postgres:
    image: rttomlinson/bets-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'mysecretpassword'
