process.env.AUTH0_SECRET = 'session_secret';
process.env.AUTH0_ISSUER_BASE_URL = 'https://acme.auth0.local';
process.env.AUTH0_BASE_URL = 'http://www.acme.com/';
process.env.AUTH0_CLIENT_ID = 'client_id';
process.env.AUTH0_CLIENT_SECRET = 'client_secret';
process.env.AUTH0_AUDIENCE = 'Test-API';
process.env.AUTH0_SCOPE = 'openid profile email read:shows';
process.env.AUTH0_SECRET = '8a6014e154294d644230f8270000950bc611d3e9876f30a6e69ae5544baa8333';
process.env.AUTH0_BASE_URL = 'http://localhost:3000';
process.env.AUTH0_ISSUER_BASE_URL = 'https://dev-6zbkrgtguww4sp3s.us.auth0.com';
process.env.AUTH0_CLIENT_ID = 'C3YRvW2SPqgUMmo6i3t9YMXqeamaFfCH';
process.env.AUTH0_CLIENT_SECRET = '4CR88PQOJcT-LX6kMH677Vqy2kHNCortF9fNePXxCvbBEvHmZId4Wwux5Mp7ZmpJ';
process.env.POSTGRES_URL = 'postgres://postgres:mysecretpassword@localhost:5432/betsapp';
process.env.POSTGRES_USER = 'postgres';
process.env.POSTGRES_HOST = 'localhost';
process.env.POSTGRES_PASSWORD = 'mysecretpassword';
process.env.POSTGRES_DATABASE = 'betsapp';
process.env.POSTGRES_PORT = '5432';
process.env.SUPABASE_POSTGRES_PASSWORD = 'adDdPdCTx1P4X1AS';

process.env.KV_USE_TLS = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = 'AIzaSyCTTUHrdhAzWijcJc2HQfOtJGbhdpXB750';
